### ISSUE TITLE
Facing issue while installing strongloop on RHEL 7.1

### ISSUE THREAD

**Issue by ghatwala** [strongloop/loopback#1728]
Hi All,

Facing below error while installing strongloop on RHEL . My npm version is :
 [user1@pts00433-vm29 ~]$ npm -v
3.3.6
Node version is : 
[user1@pts00433-vm29 ~]$ node -v
v4.2.0
Next to install strongloop using "npm" , i tried below 
[user1@pts00433-vm29 ~]$ npm install -g strongloop
Just copying last few lines here ... 
 "
make: Entering directory `/home/user1/.node_modules_global/lib/node_modules/strongloop/node_modules/strong-fork-syslog/build'
  CXX(target) Release/obj.target/syslog/syslog.o
In file included from ../syslog.cc:2:0:
../compat-inl.h: In static member function âstatic void compat::CpuProfiler::StartCpuProfiling(v8::Isolate*, v8::Local<v8::String>)â:
../compat-inl.h:288:37: error: âclass v8::CpuProfilerâ has no member named âStartCpuProfilingâ
   return isolate->GetCpuProfiler()->StartCpuProfiling(title, record_samples);
                                     ^
../compat-inl.h:288:76: error: return-statement with a value, in function returning 'void' [-fpermissive]
   return isolate->GetCpuProfiler()->StartCpuProfiling(title, record_samples);
                                                                            ^
../compat-inl.h: In static member function âstatic const v8::CpuProfile* compat::CpuProfiler::StopCpuProfiling(v8::Isolate*, v8::Local<v8::String>)â:
../compat-inl.h:294:37: error: âclass v8::CpuProfilerâ has no member named âStopCpuProfilingâ
   return isolate->GetCpuProfiler()->StopCpuProfiling(title);
                                     ^
../compat-inl.h: In static member function âstatic const v8::HeapSnapshot* compat::HeapProfiler::TakeHeapSnapshot(v8::Isolate*, v8::Local<v8::String>)â:
../compat-inl.h:310:60: error: no matching function for call to âv8::HeapProfiler::TakeHeapSnapshot(v8::Local<v8::String>&)â
   return isolate->GetHeapProfiler()->TakeHeapSnapshot(title);
                                                            ^
../compat-inl.h:310:60: note: candidate is:
In file included from ../compat.h:20:0,
                 from ../node-syslog.h:13,
                 from ../syslog.cc:1:
/home/user1/.node-gyp/4.2.0/include/node/v8-profiler.h:486:23: note: const v8::HeapSnapshot* v8::HeapProfiler::TakeHeapSnapshot(v8::ActivityControl*, v8::HeapProfiler::ObjectNameResolver*)
   const HeapSnapshot* TakeHeapSnapshot(
                       ^
/home/user1/.node-gyp/4.2.0/include/node/v8-profiler.h:486:23: note:   no known conversion for argument 1 from âv8::Local<v8::String>â to âv8::ActivityControl*â
In file included from ../syslog.cc:2:0:
../compat-inl.h: In static member function âstatic const v8::CpuProfile* compat::CpuProfiler::StopCpuProfiling(v8::Isolate*, v8::Local<v8::String>)â:
../compat-inl.h:295:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/syslog/syslog.o] Error 1
make: Leaving directory `/home/user1/.node_modules_global/lib/node_modules/strongloop/node_modules/strong-fork-syslog/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user1/.node_modules_global/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-210.ael7a.ppc64le
gyp ERR! command "/usr/local/bin/node" "/home/user1/.node_modules_global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user1/.node_modules_global/lib/node_modules/strongloop/node_modules/strong-fork-syslog
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:strong-fork-syslog strong-fork-syslog@1.2.3 install: `node-gyp rebuild`
npm WARN install:strong-fork-syslog Exit status 1

npm ERR! code 1

"

**Comment by superkhau** [comment]
@rmg ^

**Comment by rmg** [comment]
There's a bug in npm@3 (apparently fixed in 3.3.7, though I haven't verified it myself yet) that results in optionalDependencies not being treated as optional, which is what is happening here.

See #1722, #1685, strongloop/strongloop#253, and finally npm/npm#9643.

You should either upgrade to npm@next (currently 3.3.8) or downgrade to npm@2.

Unrelated, you should also upgrade node to v4.2.1, especially if you happen to be using mysql (see felixge/node-mysql#1236, nodejs/node#3331).

**Comment by rmg** [comment]
@ghatwala once you've had a chance to confirm, please close this issue if my comment above resolves your problem.

**Comment by mattwoolnough** [comment]
I'm also seeing same issue on Ubuntu 15.04

matt@linux:~$  npm -v
2.14.7
matt@linux:~$ node -v
v4.2.1

```
make: Entering directory '/usr/lib/node_modules/strongloop/node_modules/strong-arc/node_modules/strong-pm/node_modules/strong-supervisor/node_modules/strong-fork-syslog/build'
  CXX(target) Release/obj.target/syslog/syslog.o
In file included from ../syslog.cc:2:0:
../compat-inl.h: In static member function ‘static void compat::CpuProfiler::StartCpuProfiling(v8::Isolate*, v8::Local<v8::String>)’:
../compat-inl.h:288:37: error: ‘class v8::CpuProfiler’ has no member named ‘StartCpuProfiling’
   return isolate->GetCpuProfiler()->StartCpuProfiling(title, record_samples);
                                     ^
../compat-inl.h:288:76: error: return-statement with a value, in function returning 'void' [-fpermissive]
   return isolate->GetCpuProfiler()->StartCpuProfiling(title, record_samples);
                                                                            ^
../compat-inl.h: In static member function ‘static const v8::CpuProfile* compat::CpuProfiler::StopCpuProfiling(v8::Isolate*, v8::Local<v8::String>)’:
../compat-inl.h:294:37: error: ‘class v8::CpuProfiler’ has no member named ‘StopCpuProfiling’
   return isolate->GetCpuProfiler()->StopCpuProfiling(title);
                                     ^
```

**Comment by ghatwala** [comment]
Hi ,

I have tried the downgrade to npm 2 , but problem still persists.
Could you let me know the best fit versions of npm , node which helps in installing strongloop ?

Regards,
Amit

**Comment by rmg** [comment]
@ghatwala what is the error message when installing using npm 2?

**Comment by heralight** [comment]
work well with node v5.0.0 (npm v3.3.12) on ubuntu 14.04
nvm install 5
run this : npm install -g strongloop  --no-optional

**Comment by EthraZa** [comment]
Just have the same problem installing on an Amazon Linux with nvm.
Using 4.2.2 is a no go to install Strongloop.
Using 5.0.0 it installed ok. But I don't yet found how to get the slc command line working!

**Comment by superkhau** [comment]
@ghatwala @EthraZa @mattwoolnough Are you guys still running into issues? Can I close this?

**Comment by ghatwala** [comment]
@superkhau  - It's resolved for me !!!

**Comment by superkhau** [comment]
@ghatwala Nice, glad its working for you guys now.
